name: Build & Test

on: [push, pull_request]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Run cross-version tests
        run: sbt ^test
      - name: Run cross-version local publish
        run: sbt ^publishLocal
      - name: Run coverage
        run: sbt coverage test
      - name: Coverage Report
        run: sbt coverageReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.0.1
